/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen1_oliveriraheta;

import java.awt.Color;
import java.util.ArrayList;
import java.util.Scanner;
import javax.swing.JOptionPane;

/**
 *
 * @author Oliver Iraheta
 */
public class F_Main extends javax.swing.JFrame {

    /**
     * Creates new form F_Main
     */
    public static Scanner rm = new Scanner(System.in);

    public F_Main() {
        initComponents();
        this.setLocationRelativeTo(null);
        F_crud.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        F_crud = new javax.swing.JFrame();
        tp_crud = new javax.swing.JTabbedPane();
        p_agregar = new javax.swing.JPanel();
        L_IP = new javax.swing.JLabel();
        L_IP2 = new javax.swing.JLabel();
        tf_ip = new javax.swing.JTextField();
        tf_mask = new javax.swing.JTextField();
        tf_hostname = new javax.swing.JTextField();
        b_agregar = new javax.swing.JButton();
        tp_tipoPc = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        L_IP3 = new javax.swing.JLabel();
        L_IP4 = new javax.swing.JLabel();
        L_IP5 = new javax.swing.JLabel();
        L_IP6 = new javax.swing.JLabel();
        B_SSD = new javax.swing.JRadioButton();
        B_HDD = new javax.swing.JRadioButton();
        tf_ram = new javax.swing.JTextField();
        tf_almacenamiento = new javax.swing.JTextField();
        cb_grafica = new javax.swing.JCheckBox();
        jPanel4 = new javax.swing.JPanel();
        L_IP1 = new javax.swing.JLabel();
        L_IP8 = new javax.swing.JLabel();
        L_IP9 = new javax.swing.JLabel();
        tf_pantalla = new javax.swing.JTextField();
        tf_marca = new javax.swing.JTextField();
        cb_rgb = new javax.swing.JCheckBox();
        L_IP7 = new javax.swing.JLabel();
        p_listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ta_listar = new javax.swing.JTextArea();
        p_eliminar = new javax.swing.JPanel();
        cb_eliminar = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        bg_tipoAlma = new javax.swing.ButtonGroup();
        P_main = new javax.swing.JPanel();
        b_ingresar = new javax.swing.JButton();
        b_crud = new javax.swing.JButton();

        F_crud.setSize(new java.awt.Dimension(751, 546));

        tp_crud.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tp_crudStateChanged(evt);
            }
        });

        L_IP.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP.setText("Dirección IP");

        L_IP2.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP2.setText("Mascara de red");

        tf_ip.setForeground(new java.awt.Color(153, 153, 153));
        tf_ip.setText("Ej: 000.000.0.00");
        tf_ip.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_ip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_ip.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_ipMouseClicked(evt);
            }
        });
        tf_ip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ipActionPerformed(evt);
            }
        });

        tf_mask.setForeground(new java.awt.Color(153, 153, 153));
        tf_mask.setText("Ej: 000.000.0.00");
        tf_mask.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_mask.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_mask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_maskMouseClicked(evt);
            }
        });

        tf_hostname.setForeground(new java.awt.Color(153, 153, 153));
        tf_hostname.setText("Ej: Nuila");
        tf_hostname.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_hostname.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_hostname.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_hostnameMouseClicked(evt);
            }
        });

        b_agregar.setBackground(new java.awt.Color(255, 0, 51));
        b_agregar.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        b_agregar.setText("AGREGAR");
        b_agregar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_agregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_agregarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                b_agregarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                b_agregarMouseExited(evt);
            }
        });

        L_IP3.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP3.setText("Almacenamiento");

        L_IP4.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP4.setText("RAM");

        L_IP5.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP5.setText("Tarjeta Grafica");

        L_IP6.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP6.setText("Tipo almacenamiento");

        bg_tipoAlma.add(B_SSD);
        B_SSD.setText("SDD");

        bg_tipoAlma.add(B_HDD);
        B_HDD.setText("HDD");

        tf_ram.setForeground(new java.awt.Color(153, 153, 153));
        tf_ram.setText("Ej: 32");
        tf_ram.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_ram.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_ram.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_ramMouseClicked(evt);
            }
        });
        tf_ram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_ramActionPerformed(evt);
            }
        });

        tf_almacenamiento.setForeground(new java.awt.Color(153, 153, 153));
        tf_almacenamiento.setText("Ej: 500");
        tf_almacenamiento.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_almacenamiento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_almacenamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_almacenamientoMouseClicked(evt);
            }
        });
        tf_almacenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tf_almacenamientoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(L_IP6, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49)
                        .addComponent(B_SSD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(B_HDD, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(L_IP3, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(L_IP4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tf_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(L_IP5, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(cb_grafica, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(L_IP4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tf_ram, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(L_IP3)
                        .addGap(18, 18, 18))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(tf_almacenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_IP6)
                    .addComponent(B_SSD)
                    .addComponent(B_HDD))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(L_IP5)
                    .addComponent(cb_grafica))
                .addGap(60, 60, 60))
        );

        tp_tipoPc.addTab("ESCRITORIO", jPanel1);

        L_IP1.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP1.setText("Marca");

        L_IP8.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP8.setText("RGB");

        L_IP9.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP9.setText("Def. Pantalla");

        tf_pantalla.setForeground(new java.awt.Color(153, 153, 153));
        tf_pantalla.setText("Ej: 1920x1080");
        tf_pantalla.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_pantalla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_pantalla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_pantallaMouseClicked(evt);
            }
        });

        tf_marca.setForeground(new java.awt.Color(153, 153, 153));
        tf_marca.setText("Ej: HP");
        tf_marca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tf_marca.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tf_marca.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tf_marcaMouseClicked(evt);
            }
        });

        cb_rgb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_rgbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(L_IP9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                    .addComponent(L_IP1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(L_IP8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_rgb, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_IP1)
                    .addComponent(tf_marca, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_IP9)
                    .addComponent(tf_pantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(L_IP8)
                    .addComponent(cb_rgb))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        tp_tipoPc.addTab("LAPTOP", jPanel4);

        L_IP7.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        L_IP7.setText("Hostname");

        javax.swing.GroupLayout p_agregarLayout = new javax.swing.GroupLayout(p_agregar);
        p_agregar.setLayout(p_agregarLayout);
        p_agregarLayout.setHorizontalGroup(
            p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_agregarLayout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(tp_tipoPc, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(p_agregarLayout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(L_IP2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(L_IP, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(74, 74, 74)
                .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_hostname, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tf_mask, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                .addComponent(b_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38))
            .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_agregarLayout.createSequentialGroup()
                    .addGap(65, 65, 65)
                    .addComponent(L_IP7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );
        p_agregarLayout.setVerticalGroup(
            p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_agregarLayout.createSequentialGroup()
                .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(p_agregarLayout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(L_IP)
                            .addComponent(tf_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(L_IP2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tf_mask, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tf_hostname, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, p_agregarLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(b_agregar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)))
                .addComponent(tp_tipoPc, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(p_agregarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(p_agregarLayout.createSequentialGroup()
                    .addGap(141, 141, 141)
                    .addComponent(L_IP7)
                    .addContainerGap(351, Short.MAX_VALUE)))
        );

        tp_crud.addTab("AGREGAR", p_agregar);

        ta_listar.setColumns(20);
        ta_listar.setRows(5);
        jScrollPane1.setViewportView(ta_listar);

        javax.swing.GroupLayout p_listarLayout = new javax.swing.GroupLayout(p_listar);
        p_listar.setLayout(p_listarLayout);
        p_listarLayout.setHorizontalGroup(
            p_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_listarLayout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        p_listarLayout.setVerticalGroup(
            p_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_listarLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        tp_crud.addTab("LISTAR", p_listar);

        javax.swing.GroupLayout p_eliminarLayout = new javax.swing.GroupLayout(p_eliminar);
        p_eliminar.setLayout(p_eliminarLayout);
        p_eliminarLayout.setHorizontalGroup(
            p_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_eliminarLayout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(118, Short.MAX_VALUE))
        );
        p_eliminarLayout.setVerticalGroup(
            p_eliminarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(p_eliminarLayout.createSequentialGroup()
                .addGap(89, 89, 89)
                .addComponent(cb_eliminar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(414, Short.MAX_VALUE))
        );

        tp_crud.addTab("ELIMINAR", p_eliminar);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 755, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 525, Short.MAX_VALUE)
        );

        tp_crud.addTab("<", jPanel2);

        javax.swing.GroupLayout F_crudLayout = new javax.swing.GroupLayout(F_crud.getContentPane());
        F_crud.getContentPane().setLayout(F_crudLayout);
        F_crudLayout.setHorizontalGroup(
            F_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_crud, javax.swing.GroupLayout.DEFAULT_SIZE, 759, Short.MAX_VALUE)
        );
        F_crudLayout.setVerticalGroup(
            F_crudLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tp_crud, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        setSize(new java.awt.Dimension(1915, 636));

        P_main.setBackground(new java.awt.Color(255, 255, 51));

        b_ingresar.setBackground(new java.awt.Color(102, 102, 102));
        b_ingresar.setForeground(new java.awt.Color(255, 255, 255));
        b_ingresar.setText("INGRESAR PC");
        b_ingresar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                b_ingresarMouseClicked(evt);
            }
        });

        b_crud.setBackground(new java.awt.Color(102, 102, 102));
        b_crud.setForeground(new java.awt.Color(255, 255, 255));
        b_crud.setText("CRUD PC");
        b_crud.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_crud.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b_crud.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_crudActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout P_mainLayout = new javax.swing.GroupLayout(P_main);
        P_main.setLayout(P_mainLayout);
        P_mainLayout.setHorizontalGroup(
            P_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(P_mainLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(P_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(b_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        P_mainLayout.setVerticalGroup(
            P_mainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, P_mainLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(b_crud, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)
                .addComponent(b_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(58, 58, 58))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(P_main, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b_crudActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_crudActionPerformed
        this.setVisible(false);
        F_crud.setVisible(true);

    }//GEN-LAST:event_b_crudActionPerformed

    private void tp_crudStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tp_crudStateChanged
        if (tp_crud.getSelectedIndex() == 0) {
            tf_ip.setText("  Ej: 000.000.0.00");
            tf_ip.setForeground(Color.gray);
            tf_hostname.setText("  Ej: Nuila");
            tf_hostname.setForeground(Color.gray);
            tf_mask.setText("  Ej: 000.000.0.00");
            tf_mask.setForeground(Color.gray);
            tf_almacenamiento.setText(" Ej: 500");
            tf_almacenamiento.setForeground(Color.gray);
            tf_ram.setText(" Ej: 32");
            tf_ram.setForeground(Color.gray);
            tf_pantalla.setText(" Ej: 1920x1080");
            tf_pantalla.setForeground(Color.gray);
            tf_marca.setText(" Ej: HP");
            tf_marca.setForeground(Color.gray);
        }
        if (tp_crud.getSelectedIndex() == 1) {
            String listar = "";
            for (PC pc : pcs) {

                listar += pcs.indexOf(pc) + ")\n" + pc + "\n";
            }
            ta_listar.setText(listar);
        }
        if (tp_crud.getSelectedIndex() == 3) {
            F_crud.setVisible(false);
            this.setVisible(true);
            
        }
    }//GEN-LAST:event_tp_crudStateChanged


    private void tf_ipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ipActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ipActionPerformed

    private void b_agregarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarMouseEntered
        b_agregar.setForeground(Color.WHITE);
    }//GEN-LAST:event_b_agregarMouseEntered

    private void b_agregarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarMouseExited
        b_agregar.setForeground(Color.BLACK);
    }//GEN-LAST:event_b_agregarMouseExited

    private void tf_ipMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ipMouseClicked
        tf_ip.setText("");
        tf_ip.setForeground(Color.black);
    }//GEN-LAST:event_tf_ipMouseClicked

    private void tf_maskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_maskMouseClicked
        tf_mask.setText("");
        tf_mask.setForeground(Color.black);
    }//GEN-LAST:event_tf_maskMouseClicked

    private void tf_hostnameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_hostnameMouseClicked
        // TODO add your handling code here:
        tf_hostname.setText("");
        tf_hostname.setForeground(Color.black);
    }//GEN-LAST:event_tf_hostnameMouseClicked

    private void tf_ramMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_ramMouseClicked
        tf_ram.setText("");
        tf_ram.setForeground(Color.black);
    }//GEN-LAST:event_tf_ramMouseClicked

    private void tf_ramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_ramActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tf_ramActionPerformed

    private void tf_almacenamientoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_almacenamientoMouseClicked
        // TODO add your handling code here:
        tf_almacenamiento.setText("");
        tf_almacenamiento.setForeground(Color.black);
    }//GEN-LAST:event_tf_almacenamientoMouseClicked

    private void tf_almacenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tf_almacenamientoActionPerformed

    }//GEN-LAST:event_tf_almacenamientoActionPerformed

    private void tf_pantallaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_pantallaMouseClicked
        tf_pantalla.setText("");
        tf_pantalla.setForeground(Color.black);
    }//GEN-LAST:event_tf_pantallaMouseClicked

    private void tf_marcaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tf_marcaMouseClicked
        tf_marca.setText("");
        tf_marca.setForeground(Color.black);
    }//GEN-LAST:event_tf_marcaMouseClicked

    private void cb_rgbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_rgbActionPerformed

    }//GEN-LAST:event_cb_rgbActionPerformed

    private void b_agregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_agregarMouseClicked
        if (tp_tipoPc.getSelectedIndex() == 0) {
            String tipo = "SDD";
            if (B_HDD.isSelected()) {
                tipo = "HDD";
            }
            boolean x = false;
            if (cb_grafica.isSelected()) {
                x = true;
            }
            pcs.add(new Escritorio(Integer.parseInt(tf_ram.getText()),
                    Integer.parseInt(tf_almacenamiento.getText()),
                    tipo, x, tf_ip.getText(), tf_mask.getText(), tf_hostname.getText()));
        } else {
            boolean x = false;
            if (cb_rgb.isSelected()) {
                x = true;
            }
            pcs.add(new Laptop(tf_marca.getText(), tf_pantalla.getText(), x, tf_ip.getText(), tf_mask.getText(), tf_hostname.getText()));
        }
        JOptionPane.showMessageDialog(this, "Pc agregada exitosamente");
        tp_crud.setSelectedIndex(1);
        tp_crud.setSelectedIndex(0);
        

    }//GEN-LAST:event_b_agregarMouseClicked

    private void b_ingresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_b_ingresarMouseClicked
        boolean y = true;
            String ipIngresar = JOptionPane.showInputDialog("Ingrese IP");
            boolean x = false;
         
            int pcIndex = 0;
            for (PC pc : pcs) {
                if (pc.getIp().equals(ipIngresar)) {
                    x = true;
                    pcIndex = pcs.indexOf(pc);
                }
            }
            if (!x) {
                JOptionPane.showMessageDialog(this, "IP NO ENCONTRADO");
            }else{
                while (y) {
                System.out.print("\n"+pcs.get(pcIndex).getHostname()+"# ");
                rm = new Scanner(System.in);
                String opc = rm.nextLine().toLowerCase();
                switch(opc){
                    case "ping"->{
                        
                    }
                    case "show"->{
                        System.out.println(pcs.get(pcIndex));
                    }
                    case "exit"->{
                        y = false;
                    }
                    default -> JOptionPane.showMessageDialog(this,"OPCION NO VALIDA");
                }
            }
        }
    }//GEN-LAST:event_b_ingresarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(F_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(F_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(F_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(F_Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new F_Main().setVisible(true);
            }
        });
    }
    //arraylist
    ArrayList<PC> pcs = new ArrayList();
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton B_HDD;
    private javax.swing.JRadioButton B_SSD;
    private javax.swing.JFrame F_crud;
    private javax.swing.JLabel L_IP;
    private javax.swing.JLabel L_IP1;
    private javax.swing.JLabel L_IP2;
    private javax.swing.JLabel L_IP3;
    private javax.swing.JLabel L_IP4;
    private javax.swing.JLabel L_IP5;
    private javax.swing.JLabel L_IP6;
    private javax.swing.JLabel L_IP7;
    private javax.swing.JLabel L_IP8;
    private javax.swing.JLabel L_IP9;
    private javax.swing.JPanel P_main;
    private javax.swing.JButton b_agregar;
    private javax.swing.JButton b_crud;
    private javax.swing.JButton b_ingresar;
    private javax.swing.ButtonGroup bg_tipoAlma;
    private javax.swing.JComboBox<String> cb_eliminar;
    private javax.swing.JCheckBox cb_grafica;
    private javax.swing.JCheckBox cb_rgb;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel p_agregar;
    private javax.swing.JPanel p_eliminar;
    private javax.swing.JPanel p_listar;
    private javax.swing.JTextArea ta_listar;
    private javax.swing.JTextField tf_almacenamiento;
    private javax.swing.JTextField tf_hostname;
    private javax.swing.JTextField tf_ip;
    private javax.swing.JTextField tf_marca;
    private javax.swing.JTextField tf_mask;
    private javax.swing.JTextField tf_pantalla;
    private javax.swing.JTextField tf_ram;
    private javax.swing.JTabbedPane tp_crud;
    private javax.swing.JTabbedPane tp_tipoPc;
    // End of variables declaration//GEN-END:variables
}
